export {default as Navbar} from './Navbar'
export {default as Footer} from './Footer'
export {default as Hero} from './Hero'
export {default as Testimonials} from './Testimonials'
export {default as Team} from './Team'
export {default as Pricing} from './Pricing'
export {default as Contact} from './Contact'